version: '2'
services:
    fistjhipster-app:
        image: fistjhipster
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://fistjhipster-mysql:3306/fistjhipster?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    fistjhipster-mysql:
        extends:
            file: mysql.yml
            service: fistjhipster-mysql
